In [18]:
import numpy as np

grid = [[9,0,6,0,7,0,4,0,3],
        [0,0,0,4,0,0,2,0,0],
        [0,7,0,0,2,3,0,1,0],
        [5,0,0,0,0,0,1,0,0],
        [0,4,0,2,0,8,0,6,0],
        [0,0,3,0,0,0,0,0,5],
        [0,3,0,7,0,0,0,5,0],
        [0,0,7,0,0,5,0,0,0],
        [4,0,5,0,1,0,7,0,8]]

def possible(row, column, number):
    global grid
    #Is the number appearing in the given row?
    for i in range(0,9):
        if grid[row][i] == number:
            return False

    #Is the number appearing in the given column?
    for i in range(0,9):
        if grid[i][column] == number:
            return False
    
    #Is the number appearing in the given square?
    x = (column // 3) * 3
    y = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y+i][x+j] == number:
                return False

    return True

def solve():
    global grid
    for row in range(0,9):
        for column in range(0,9):
            if grid[row][column] == 0:
                for number in range(1,10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        solve()
                        grid[row][column] = 0

                return
      
    print(np.matrix(grid))
    input('Press ENTER to see more possible solutions')

solve()

[[9 2 6 5 7 1 4 8 3]
 [3 5 1 4 8 6 2 7 9]
 [8 7 4 9 2 3 5 1 6]
 [5 8 2 3 6 7 1 9 4]
 [1 4 9 2 5 8 3 6 7]
 [7 6 3 1 4 9 8 2 5]
 [2 3 8 7 9 4 6 5 1]
 [6 1 7 8 3 5 9 4 2]
 [4 9 5 6 1 2 7 3 8]]
Press ENTER to see more possible solutions
[[9 2 6 5 7 1 4 8 3]
 [3 5 1 4 8 6 2 7 9]
 [8 7 4 9 2 3 5 1 6]
 [5 8 2 3 6 7 1 9 4]
 [1 4 9 2 5 8 3 6 7]
 [7 6 3 1 9 4 8 2 5]
 [2 3 8 7 4 9 6 5 1]
 [6 1 7 8 3 5 9 4 2]
 [4 9 5 6 1 2 7 3 8]]
Press ENTER to see more possible solutions
